XETutGlobalXAppV1/Controllers/XETutGlobalXController.cs
using Microsoft.AspNetCore.Mvc;
using XEtutGlobalX.Modal.Material;
using Newtonsoft.Json;
using System.Net.NetworkInformation;
using System.Data.Common;
using System.Net;
using System.Net.Mail;
using static XETutGlobalXAppV1.AppCode.XETutGlobalX_ConnectDB.DBConnect_Mode;
using System.Data;
using XEtutGlobalX.Modal.XETutGlobalX_DB.Request;
using XETutGlobalX.DAL.XETutGlobalX_DB;
using Microsoft.AspNetCore.Cryptography.KeyDerivation;
using System.Security.Cryptography;
using Azure;
using XEtutGlobalX.Modal.XETutGlobalX_DB.Response;
using Microsoft.AspNetCore.Http;
using static XEtutGlobalX.Modal.XETutGlobalX_DB.Response.WebloginValidation;
using XEtutGlobalX.Modal.XETutGlobalX_DB.Request.UserProfile;
using static System.Runtime.InteropServices.JavaScript.JSType;
using XEtutGlobalX.Modal.XETutGlobalX_DB.Response.UserProfile;
namespace XETutGlobalXAppV1.Controllers
{
    
    public class XETutGlobalXController : Controller
    {
        private readonly IConfiguration _config;
        public XETutGlobalXController(IConfiguration config)
        {
            _config = config;
        }
        public string HashPassword(string password)
        {
            // Generate a 128-bit salt using a secure PRNG
            byte[] salt = new byte[128 / 8];
            using (var rng = RandomNumberGenerator.Create())
            {
                rng.GetBytes(salt);
            }

            // Derive a 256-bit subkey (use HMACSHA256 with 100,000 iterations)
            string hashed = Convert.ToBase64String(KeyDerivation.Pbkdf2(
                password: password,
                salt: salt,
                prf: KeyDerivationPrf.HMACSHA256,
                iterationCount: 100000,
                numBytesRequested: 256 / 8));

            // Combine the salt and password hash
            return $"{Convert.ToBase64String(salt)}:{hashed}";
        }
        /// <summary>
        /// This Function is used for Load LoginX Views.
        /// </summary>
        /// <returns></returns>
        public IActionResult LoginX()
        {
            return View("LoginX");
        }
        [HttpPost]
        public IActionResult BindCity(string StateCode, string CountryCode)
        {
            bool status = true;
            CityDetails cityDetails = new CityDetails();
            List<CitySet> citySets = new List<CitySet>();
            object citySet = new();
            try
            {
                using (StreamReader r = new StreamReader("Material-Json/cities.json"))
                {
                    string json = r.ReadToEnd();

                    cityDetails.citySets = JsonConvert.DeserializeObject<List<CitySet>>(json!)!;
                    //countryState = countryStateDetails.countries;
                    //User item = JsonConvert.DeserializeObject<User>(json);
                }
                if (cityDetails.citySets != null)
                {
                    for (int i = 0; i < cityDetails.citySets.Count; i++)
                    {
                        if (cityDetails.citySets[i].state_code == StateCode && cityDetails.citySets[i].country_code == CountryCode)
                        {
                            citySets.Add(new CitySet
                            {
                                code = cityDetails.citySets[i].name,
                                name = cityDetails.citySets[i].name,
                                

                            });
                        }
                    }
                    citySet = citySets;
                }
            }
            catch (Exception ex)
            {
                status = false;
                return Json(new
                {
                    IsSuccess = status,
                    Error = ex.Message
                });
            }
            return Json(new
            {
                IsSuccess = status,
                citySet = citySet
            });
        }
        [HttpPost]
        public IActionResult BindState(string CountryCode)
        {
            bool status = true;
            List<State> states = new List<State>();
            CountryStateDetails countryStateDetails = new CountryStateDetails();
            object countryState = new();
            try
            {
                using (StreamReader r = new StreamReader("Material-Json/countries+states.json"))
                {
                    string json = r.ReadToEnd();

                    countryStateDetails.countries = JsonConvert.DeserializeObject<List<Country>>(json!)!;
                    countryState = countryStateDetails.countries;
                    //User item = JsonConvert.DeserializeObject<User>(json);
                }
                if(countryStateDetails.countries != null)
                {
                    for(int i = 0; i < countryStateDetails.countries.Count; i++)
                    {
                        if (countryStateDetails.countries[i].iso2 == CountryCode)
                        {
                            states = countryStateDetails.countries[i].states;
                        }
                    }
                    countryState = states;
                }
            }
            catch (Exception ex)
            {
                status = false;
                return Json(new
                {
                    IsSuccess = status,
                    Error = ex.Message
                });
            }
            return Json(new
            {
                IsSuccess = status,
                stateDetails = countryState
            });
        }
        [HttpGet]
        public IActionResult GetAdminDesignations()
        {
            bool status = true;
            List<Designation> designations = new List<Designation>();
            List<Designation> admin_designations = new List<Designation>();
            object obj_admin_designations = new();
            try
            {
                if (HttpContext.Session.GetString("DesignationList") != null)
                {
                    string json = HttpContext.Session.GetString("DesignationList")!;
                    designations = JsonConvert.DeserializeObject<List<Designation>>(json)!;
                }
                else
                {
                    BindDesignation();
                    string json = HttpContext.Session.GetString("DesignationList")!;
                    designations = JsonConvert.DeserializeObject<List<Designation>>(json)!;
                }
                if (designations != null)
                {
                    foreach (Designation designation in designations)
                    {
                        if (designation != null)
                        {
                            if (designation.Designation_Code == "CEO" || designation.Designation_Code == "CTO")
                            {
                                admin_designations.Add(designation);
                                obj_admin_designations = admin_designations;
                            }
                           
                        }
                        else
                        {
                            obj_admin_designations = null!;
                        }
                    }
                }
            }
            catch(Exception ex)
            {
                status = false;
                return Json(new
                {
                    IsSuccess = status,
                    Error = ex.Message
                });
            }
            
            return Json(new {
                IsSuccess = true,
                admin_designations = obj_admin_designations,
            
            });
        }
        [HttpPost]
        public IActionResult BindDesignation()
        {
            bool status = true;
            string DBConnect = string.Empty;
            string DataSource = string.Empty;
            string InitialCatalog = string.Empty;
            string IntegratedSecurity = string.Empty;
            string Encrypt = string.Empty;
            string TrustServerCertificate= string.Empty;
            object objdesignations = new();
            DataSet dsDesignation = new();
            List<Designation> designations = new List<Designation>();
            XETutGlobalX.DAL.XETutGlobalX_DB.clsDesignation clsDesignation = new();
            try
            {
                DBConnectMode mode = _config.GetValue<DBConnectMode>("DBSetting:mode")!;
  
                switch (mode)
                {
                    case DBConnectMode.Simple:
                        DBConnect = _config.GetValue<string>("DBSetting:ConnectionString")!;
                        dsDesignation = clsDesignation.GetDesignation(DBConnect, (XETutGlobalX.DAL.App_Code.DBConnectMode.DBConnect_Mode)mode);
                        break;
                    case DBConnectMode.Complex:
                        DataSource = _config.GetValue<string>("DBSetting:DataSource")!;
                        InitialCatalog = _config.GetValue<string>("DBSetting:DataSource")!;
                        IntegratedSecurity = _config.GetValue<string>("DBSetting:IntegratedSecurity")!;
                        Encrypt = _config.GetValue<string>("DBSetting:Encrypt")!;
                        TrustServerCertificate = _config.GetValue<string>("DBSetting:TrustServerCertificate")!;
                        DBConnect = DataSource + ";" + InitialCatalog + ";" + IntegratedSecurity + ";" + Encrypt +";" +  TrustServerCertificate + ";";
                        dsDesignation = clsDesignation.GetDesignation(DBConnect, (XETutGlobalX.DAL.App_Code.DBConnectMode.DBConnect_Mode)mode);
                        break;
                }
                if (dsDesignation != null)
                {
                    if(dsDesignation.Tables!=null)
                    {
                        if (dsDesignation.Tables.Count > 0)
                        {
                            if (dsDesignation.Tables[0].Rows.Count > 0)

XETutGlobalXAppV1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - XETutGlobalXAppV1</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="icon" href="~/Images/GMETECH_XETUT_Work-copy.png" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/XETutGlobalXAppV1.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/fontawesome.min.css" integrity="sha512-d0olNN35C6VLiulAobxYHZiXJmq+vl+BGIgAxQtD5+kqudro/xNMvv2yIHAciGHpExsIbKX3iLg+0B6d0k4+ZA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/fontawesome.min.css" integrity="sha512-d0olNN35C6VLiulAobxYHZiXJmq+vl+BGIgAxQtD5+kqudro/xNMvv2yIHAciGHpExsIbKX3iLg+0B6d0k4+ZA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" integrity="sha512-vKMx8UnXk60zUwyUnUPM3HbQo8QfmNx7+ltw8Pm5zLusl1XIfwcxo8DbWCqMGKaWeNxWA8yrx5v3SaVpMvR3CA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap-datepicker.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/loadingio/ldloader@v1.0.0/dist/ldld.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/intl-tel-input/23.1.1/css/intlTelInput.css" integrity="sha512-OkSoWyaoScjXhOm87XO5hDz1E5buvm2aAkq+5zJmaYpylA0OKJ5no5qc4ZRrmApoaXEgXc3n0iyVS1q5FgiJjg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://cdn3.devexpress.com/jslib/23.1.14/css/dx.light.css">
    <!-- DevExtreme libraries (reference only one of them) -->
    
    <script type="text/javascript" src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    @* <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script> *@
    <script>window.jQuery || document.write(decodeURIComponent('%3Cscript src="js/jquery.min.js"%3E%3C/script%3E'))</script>

    <!-- DevExtreme theme -->
    @* <link rel="stylesheet" href="https://cdn3.devexpress.com/jslib/23.1.14/css/dx.light.css"> *@
    <link rel="stylesheet" href="~/DevExtreme/version/24.1.10/Lib/css/dx.material.blue.light.css">


    <!-- DevExtreme libraries (reference only one of them) -->
    @* <script type="text/javascript" src="https://cdn3.devexpress.com/jslib/23.1.14/js/dx.all.js"></script> *@
    <script type="text/javascript" src="~/DevExtreme/version/23.1.14/Lib/js/dx.all.js"></script>

    <script src="~/js/hdesk-all.js" asp-append-version="true"></script>
</head>
<body class="dx-viewport" onload="BindHelpDeskForm();">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow w-100">
            <div class="container-fluid">
                
                <a class="navbar-brand d-flex" style="white-space: break-spaces;align-items: center;" asp-area="" asp-controller="Home" asp-action="Index"><img src="~/Images/XETutGlobalXSM-logo-sm-br.png" class="XETutGlobalx-Logo" />OTMS Portal</a>
                <button class="navbar-toggler me-3" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1" >
                        <li id="lnkHome" class="nav-item @ViewData["ActiveHomeTab"]">
                            <a class="nav-link text-dark text-center"  asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li id="lnkPrivacy" class="nav-item @ViewData["ActivePrivacyTab"]">
                            <a class="nav-link text-dark text-center" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li id="lnkHeplDesk" class="nav-item @ViewData["ActiveHelpDeskTab"]">
                            <a class="nav-link text-dark text-center" asp-area="" asp-controller="Home" asp-action="HelpDesk">Help</a>
                        </li>
                        <li id="lnkHeplDesk" class="nav-item @ViewData["ActiveInstPortalTab"]">
                            <a class="nav-link text-dark text-center" asp-area="" asp-controller="Home" asp-action="InstructorPortal">Instructor Portal</a>
                        </li>
                    </ul>
                    <form class="d-flex">
                        <a class="nav-link text-link XETutGlobalX-Signin pointer-cursor" asp-area="" asp-controller="XETutGlobalX" asp-action="LoginX">Sign in</a>
                        
                        <a type="button" id="btnRegisterNow" asp-area="" class="btn btn-XeTutKonnect btn-XeTutKonnect-primary padd825 font-xetutglobalx-default font-weight-bold" asp-controller="XETutGlobalX" asp-action="RegXter">Register Now</a>

                    </form>
                </div>
            </div>
            
        </nav>
    </header>
    <div class="">
        
        <div class="overflow-x-layout-body1 pb-2">

            <main role="main" class="pb-3">
                @RenderBody()
            </main>
        </div>
    </div>
    
    

    <footer class="bg-white align-middle border-top footer text-muted w-100 start-0 bottom-0 text-wrap text-center">
        <div class="container mt-2 text-secondary">
            <p>&copy @DateTime.Now.Year - XETutGlobalX Powered By - GMETECH Technology Group. <br />All Rights are Reserved</p>
        </div>
        @* <div>
            <p></p>
        </div> *@
    </footer>
    
    <link href="https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css" rel="stylesheet" />
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    
    
    <script src="~/js/XETutGlobalX_Script.js" asp-append-version="true"></script>
    <script>window.jQuery || document.write(decodeURIComponent('%3Cscript src="js/jquery.min.js"%3E%3C/script%3E'))</script>
    <script src="~/lib/bootstrap/dist/js/bootstrap-datepicker.js"></script>
    <script src="https://cdn.jsdelivr.net/gh/loadingio/ldloader@v1.0.0/dist/ldld.min.js" type="text/javascript"></script>
    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js" integrity="sha512-VEd+nq25CkR676O+pLBnDW09R7VQX9Mdiij052gVCp5yVH3jGtH70Ho/UUv4mJDsEdTvqRCFZg0NKGiojGnUCw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script type="text/javascript">
        $(function () {
            $('#datepicker').datepicker();
        });
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/js/fontawesome.min.js" integrity="sha512-C8qHv0HOaf4yoA7ISuuCTrsPX8qjolYTZyoFRKNA9dFKnxgzIHnYTOJhXQIt6zwpIFzCrRzUBuVgtC4e5K1nhA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>